// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ClearLogs():Promise<void>;

export function Connect(arg1:string,arg2:string):Promise<string>;

export function Disconnect():Promise<void>;

export function GetLocalAgent():Promise<backend.LocalAgentInfo>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetLogs():Promise<Array<backend.LogEntry>>;

export function GetRecentConnections():Promise<Array<backend.RecentConnection>>;

export function GetRelayURL():Promise<string>;

export function GetSessionInfo():Promise<backend.SessionInfo>;

export function GetSettings():Promise<backend.AppSettings>;

export function GetVersion():Promise<string>;

export function SaveSettings(arg1:backend.AppSettings):Promise<void>;

export function SendHostChat(arg1:string):Promise<void>;

export function SendInputEvent(arg1:string):Promise<string>;

export function SetRelayURL(arg1:string):Promise<void>;
