// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['backend']['App']['ClearLogs']();
}

export function Connect(arg1, arg2) {
  return window['go']['backend']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['backend']['App']['Disconnect']();
}

export function GetLocalAgent() {
  return window['go']['backend']['App']['GetLocalAgent']();
}

export function GetLocalIPs() {
  return window['go']['backend']['App']['GetLocalIPs']();
}

export function GetLogs() {
  return window['go']['backend']['App']['GetLogs']();
}

export function GetRecentConnections() {
  return window['go']['backend']['App']['GetRecentConnections']();
}

export function GetRelayURL() {
  return window['go']['backend']['App']['GetRelayURL']();
}

export function GetSessionInfo() {
  return window['go']['backend']['App']['GetSessionInfo']();
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function SendHostChat(arg1) {
  return window['go']['backend']['App']['SendHostChat'](arg1);
}

export function SendInputEvent(arg1) {
  return window['go']['backend']['App']['SendInputEvent'](arg1);
}

export function SetRelayURL(arg1) {
  return window['go']['backend']['App']['SetRelayURL'](arg1);
}
